name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-dotnet@v6
        with:
          dotnet-version: '10.0.x'

      - name: Publish
        run: dotnet publish AGCScope.csproj -p:PublishProfile=FolderProfile

      - name: Zip
        run: Compress-Archive -Path publish/* -DestinationPath AGCScope-${{ github.ref_name }}-win-x64.zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          files: AGCScope-${{ github.ref_name }}-win-x64.zip
          generate_release_notes: true